services:  
  postgresql:
    image: postgres:14
    hostname: postgresql
    environment:
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "apaajaboleh!"

  conduktor-console:
    image: conduktor/conduktor-console:latest
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    environment:
      # Enterprise license key
      # CDK_LICENSE: ""
      # External database configuration
      CDK_DATABASE_URL: "postgresql://conduktor:apaajaboleh!@postgresql:5432/conduktor-console"
      # Local admin credentials
      CDK_ADMIN_EMAIL: "<name@your_company.io>"
      CDK_ADMIN_PASSWORD: "adminP4ss!"
      # Connection to the Cortex Monitoring container
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080

  conduktor-monitoring:
    image: conduktor/conduktor-console-cortex:1.30.0
    environment:
      # Connection to the Console container
      CDK_CONSOLE-URL: "http://conduktor-console:8080"

volumes:
  pg_data: {}
  conduktor_data: {}
